<?php

/**
 * @file
 * Written by Henri MEDOT <henri.medot[AT]absyx[DOT]fr>
 * http://www.absyx.fr
 */

/**
 * Implements hook_install().().
 */
function field_readonly_install() {
  db_update('system')
    ->fields(array('weight' => 2))
    ->condition('name', 'field_readonly')
    ->execute();
}

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function field_readonly_update_7001() { }
